USE CocoDb

GO
CREATE SCHEMA Content

-- CATEGORY --
GO
CREATE TABLE Content.Category
(
	Id INT NOT NULL IDENTITY(1,1),
	Name NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(1000) NOT NULL,
	UpdatedDate DATETIME2 NOT NULL,
	UpdatedById BIGINT NOT NULL,
	CreatedDate DATETIME2 NOT NULL,
	CreatedById BIGINT NOT NULL,
	ParentCategoryId INT NULL
)

GO
ALTER TABLE Content.Category
ADD CONSTRAINT PK_Category
PRIMARY KEY (Id);

GO
ALTER TABLE Content.Category
ADD CONSTRAINT FK_Category_ParentCategory
FOREIGN KEY (ParentCategoryId) REFERENCES Content.Category(Id);

-- ARTICLE --
GO
CREATE TABLE Content.Article
(
	Id BIGINT NOT NULL IDENTITY(1,1),
	Name NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(1000) NOT NULL,
	Content NVARCHAR(MAX) NOT NULL,
	UpdatedDate DATETIME2 NOT NULL,
	UpdatedById BIGINT NOT NULL,
	CreatedDate DATETIME2 NOT NULL,
	CreatedById BIGINT NOT NULL,
	CategoryId INT NOT NULL,
	Viewed INT NOT NULL
)

GO
ALTER TABLE Content.Article
ADD CONSTRAINT PK_Article
PRIMARY KEY (Id);

GO
ALTER TABLE Content.Article
ADD CONSTRAINT FK_Article_Category
FOREIGN KEY (CategoryId) REFERENCES Content.Category(Id);

-- TAG --
GO
CREATE TABLE Content.Tag
(
	Id INT NOT NULL IDENTITY(1,1),
	Name NVARCHAR(50) NOT NULL,
	CreatedDate DATETIME2 NOT NULL,
	CreatedById BIGINT NOT NULL,
	UpdatedDate DATETIME2 NOT NULL,
	UpdatedById BIGINT NOT NULL
)

GO
ALTER TABLE Content.Tag
ADD CONSTRAINT PK_Tag
PRIMARY KEY (Id);

-- ARTICLE TAG --
GO
CREATE TABLE Content.ArticleTag
(
	ArticleId BIGINT NOT NULL,
	TagId INT NOT NULL
)

GO
ALTER TABLE Content.ArticleTag
ADD CONSTRAINT FK_ArticleTag_Article
FOREIGN KEY (ArticleId) REFERENCES Content.Article(Id);

GO
ALTER TABLE Content.ArticleTag
ADD CONSTRAINT FK_ArticleTag_Tag
FOREIGN KEY (TagId) REFERENCES Content.Tag(Id);

GO
ALTER TABLE Content.ArticleTag
ADD CONSTRAINT PK_ArticleTag
PRIMARY KEY (ArticleId, TagId);