GO
CREATE TABLE dbo.Menu
(
	Id SMALLINT NOT NULL IDENTITY(1,1),
	[Name] NVARCHAR(255) NOT NULL,
	[Url] NVARCHAR(2000) NOT NULL,
	[Description] NVARCHAR(1000),
	UpdatedDate DATETIME2 NOT NULL,
	UpdatedById BIGINT NOT NULL,
	CreatedDate DATETIME2 NOT NULL,
	CreatedById BIGINT NOT NULL,
	ParentMenuId SMALLINT NULL
)

GO
ALTER TABLE dbo.Menu
ADD CONSTRAINT PK_Menu
PRIMARY KEY (Id);

GO
ALTER TABLE dbo.Menu
ADD CONSTRAINT FK_Menu_ParentMenu
FOREIGN KEY (ParentMenuId) REFERENCES dbo.Menu(Id);

GO
CREATE SCHEMA Agri;

--GROUP--
GO
CREATE TABLE Agri.[Group](
	Id BIGINT NOT NULL IDENTITY(1,1),
	Title NVARCHAR(255) NULL,
	[Description] NVARCHAR(500) NULL,
	UpdatedDate DATETIME2 NOT NULL,
	UpdatedById BIGINT NOT NULL,
	CreatedDate DATETIME2 NOT NULL,
	CreatedById BIGINT NOT NULL
)

GO
ALTER TABLE Agri.[Group]
ADD CONSTRAINT PK_Group
PRIMARY KEY (Id);

--GROUP ROLE--
GO
CREATE TABLE Agri.[GroupRole]
(
	Id TINYINT NOT NULL IDENTITY(1,1),
	[Name] NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(1000) NULL
)

GO
ALTER TABLE Agri.[GroupRole]
ADD CONSTRAINT PK_GroupRole
PRIMARY KEY (Id);

--FARMER GROUP--
GO
CREATE TABLE Agri.UserGroup(
	UserId BIGINT NOT NULL,
	GroupId BIGINT NOT NULL,
	JoinedDate DATETIME2 NULL,
	IsJoined BIT NOT NULL,
	ApprovedById BIGINT NOT NULL
)

GO
ALTER TABLE Agri.UserGroup
ADD CONSTRAINT PK_UserGroup
PRIMARY KEY (UserId, GroupId);

GO
ALTER TABLE Agri.UserGroup
ADD CONSTRAINT FK_UserGroup_Group
FOREIGN KEY (GroupId) REFERENCES Agri.[Group](Id);

--FARM--
GO
CREATE TABLE Agri.Farm
(
	Id BIGINT NOT NULL,
	Title NVARCHAR(255) NULL,
	[Description] NVARCHAR(500) NULL,
	UpdatedDate DATETIME2 NOT NULL,
	UpdatedById BIGINT NOT NULL,
	CreatedDate DATETIME2 NOT NULL,
	CreatedById BIGINT NOT NULL
)

GO
ALTER TABLE Agri.Farm
ADD CONSTRAINT PK_Farm
PRIMARY KEY (Id);

-- FARM ROLE --
GO
CREATE TABLE Agri.[FarmRole]
(
	Id TINYINT NOT NULL IDENTITY(1,1),
	Name NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(1000) NULL
)

GO
ALTER TABLE Agri.[FarmRole]
ADD CONSTRAINT PK_FarmRole
PRIMARY KEY (Id);
--User FARM--
GO
CREATE TABLE Agri.UserFarm(
	UserId BIGINT NOT NULL,
	FarmId BIGINT NOT NULL,
	JoinedDate DATETIME2 NULL,
	IsJoined BIT NOT NULL,
	ApprovedById BIGINT NOT NULL
)

GO
ALTER TABLE Agri.UserFarm
ADD CONSTRAINT PK_UserFarm
PRIMARY KEY (UserId, FarmId);

GO
ALTER TABLE Agri.UserFarm
ADD CONSTRAINT FK_UserFarm_Farm
FOREIGN KEY (FarmId) REFERENCES Agri.Farm(Id);

--GROUP FARM--
GO
CREATE TABLE Agri.FarmGroup(
	GroupId BIGINT NOT NULL,
	FarmId BIGINT NOT NULL,
	LinkedDate DATETIME2 NOT NULL,
	IsLinked BIT NOT NULL,
	LinkedById BIGINT NOT NULL,
	ApprovedById BIGINT NOT NULL
)

GO
ALTER TABLE Agri.FarmGroup
ADD CONSTRAINT PK_FarmGroup
PRIMARY KEY (GroupId, FarmId);

GO
ALTER TABLE Agri.FarmGroup
ADD CONSTRAINT FK_FarmGroup_GroupId
FOREIGN KEY (GroupId) REFERENCES Agri.[Group](Id);

GO
ALTER TABLE Agri.FarmGroup
ADD CONSTRAINT FK_FarmGroup_Farm
FOREIGN KEY (FarmId) REFERENCES Agri.Farm(Id);
-- CATEGORY --
GO
CREATE TABLE Agri.[Catalog]
(
	Id INT NOT NULL IDENTITY(1,1),
	[Name] NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(1000) NOT NULL,
	UpdatedDate DATETIME2 NOT NULL,
	UpdatedById BIGINT NOT NULL,
	CreatedDate DATETIME2 NOT NULL,
	CreatedById BIGINT NOT NULL,
	ParentCatalogId INT NULL
)

GO
ALTER TABLE Agri.[Catalog]
ADD CONSTRAINT PK_Catalog
PRIMARY KEY (Id);

GO
ALTER TABLE Agri.[Catalog]
ADD CONSTRAINT FK_Catalog_ParentCatalog
FOREIGN KEY (ParentCatalogId) REFERENCES Agri.[Catalog](Id);

--PRODUCT--
GO
CREATE TABLE Agri.Product(
	Id BIGINT NOT NULL IDENTITY(1,1),
	[Name] NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(1000) NOT NULL,
	Content NVARCHAR(MAX) NOT NULL,
	UpdatedDate DATETIME2 NOT NULL,
	UpdatedById BIGINT NOT NULL,
	CreatedDate DATETIME2 NOT NULL,
	CreatedById BIGINT NOT NULL
)

GO
ALTER TABLE Agri.[Product]
ADD CONSTRAINT PK_Product
PRIMARY KEY (Id);

-- PRODUCT CATEGORY --
GO
CREATE TABLE Agri.Category
(
	ProductId BIGINT NOT NULL,
	CategoryId INT NOT NULL
)

GO
ALTER TABLE Agri.Category
ADD CONSTRAINT FK_Category_Catalog
FOREIGN KEY (CategoryId) REFERENCES Agri.[Catalog](Id);

GO
ALTER TABLE Agri.Category
ADD CONSTRAINT FK_Category_Product
FOREIGN KEY (ProductId) REFERENCES Agri.Product(Id);

GO
ALTER TABLE Agri.Category
ADD CONSTRAINT PK_Category
PRIMARY KEY (ProductId, CategoryId);

--FARM PRODUCT--
GO
CREATE TABLE Agri.FarmProduct(
	FarmId BIGINT NOT NULL,
	ProductId BIGINT NOT NULL,
	LinkedDate DATETIME2 NOT NULL,
	IsLinked BIT NOT NULL,
	LinkedById BIGINT NOT NULL,
	ApprovedById BIGINT NOT NULL
)

GO
ALTER TABLE Agri.FarmProduct
ADD CONSTRAINT PK_FarmProduct
PRIMARY KEY (FarmId, ProductId);

GO
ALTER TABLE Agri.FarmProduct
ADD CONSTRAINT FK_FarmProduct_Product
FOREIGN KEY (ProductId) REFERENCES Agri.Product(Id);

GO
ALTER TABLE Agri.FarmProduct
ADD CONSTRAINT FK_FarmProduct_Farm
FOREIGN KEY (FarmId) REFERENCES Agri.Farm(Id);

--PRODUCT GROUP--
GO
CREATE TABLE Agri.GroupProduct(
	GroupId BIGINT NOT NULL,
	ProductId BIGINT NOT NULL,
	LinkedDate DATETIME2 NOT NULL,
	IsLinked BIT NOT NULL,
	LinkedById BIGINT NOT NULL,
	ApprovedById BIGINT NOT NULL
)

GO
ALTER TABLE Agri.GroupProduct
ADD CONSTRAINT PK_GroupProduct
PRIMARY KEY (GroupId, ProductId);

GO
ALTER TABLE Agri.GroupProduct
ADD CONSTRAINT FK_GroupProduct_Product
FOREIGN KEY (ProductId) REFERENCES Agri.Product(Id);

GO
ALTER TABLE Agri.GroupProduct
ADD CONSTRAINT FK_GroupProduct_Group
FOREIGN KEY (GroupId) REFERENCES Agri.[Group](Id);

-- CAREER --

GO
CREATE TABLE dbo.Career
(
	Id TINYINT NOT NULL IDENTITY(1,1),
	Name NVARCHAR(10),
	[Description] NVARCHAR(1000) NOT NULL,
	UpdatedDate DATETIME2 NOT NULL,
	UpdatedById BIGINT NOT NULL,
	CreatedDate DATETIME2 NOT NULL,
	CreatedById BIGINT NOT NULL
)

GO
ALTER TABLE dbo.Career
ADD CONSTRAINT PK_Career
PRIMARY KEY (Id);
-- USER CAREER --
GO
CREATE TABLE dbo.UserCareer
(
	CareerId TINYINT NOT NULL,
	UserId BIGINT NOT NULL
)

GO
ALTER TABLE dbo.UserCareer
ADD CONSTRAINT PK_UserCareer
PRIMARY KEY (CareerId, UserId);

-- USER PHOTO --
GO 
CREATE TABLE dbo.UserPhotoType
(
	Id TINYINT NOT NULL IDENTITY(1,1),
	[Name] NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(1000)
)

GO
ALTER TABLE dbo.UserPhotoType
ADD CONSTRAINT PK_UserPhotoType
PRIMARY KEY (Id);

GO
CREATE TABLE dbo.UserPhoto(
	Id BIGINT NOT NULL IDENTITY(1,1),
	Code NVARCHAR(MAX) NOT NULL,
	[Name] NVARCHAR(255) NULL,
	[Url] NVARCHAR(2000) NULL,
	[Description] NVARCHAR(1000) NULL,
	CreatedDate DATETIME2 NOT NULL,
	CreatedById BIGINT NOT NULL,
	ImageData NVARCHAR(MAX) NOT NULL,
	UserId BIGINT NOT NULL,
	TypeId TINYINT NOT NULL
)

GO
ALTER TABLE dbo.UserPhoto
ADD CONSTRAINT PK_UserPhoto
PRIMARY KEY (Id);

GO
ALTER TABLE dbo.UserPhoto
ADD CONSTRAINT FK_UserPhoto_UserPhotoType
FOREIGN KEY (TypeId) REFERENCES dbo.UserPhotoType(Id);

GO
CREATE SCHEMA Content

-- CATEGORY --
GO
CREATE TABLE Content.Category
(
	Id INT NOT NULL IDENTITY(1,1),
	Name NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(1000) NOT NULL,
	UpdatedDate DATETIME2 NOT NULL,
	UpdatedById BIGINT NOT NULL,
	CreatedDate DATETIME2 NOT NULL,
	CreatedById BIGINT NOT NULL,
	ParentCategoryId INT NULL
)

GO
ALTER TABLE Content.Category
ADD CONSTRAINT PK_Category
PRIMARY KEY (Id);

GO
ALTER TABLE Content.Category
ADD CONSTRAINT FK_Category_ParentCategory
FOREIGN KEY (ParentCategoryId) REFERENCES Content.Category(Id);

-- ARTICLE --
GO
CREATE TABLE Content.Article
(
	Id BIGINT NOT NULL IDENTITY(1,1),
	Name NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(1000) NOT NULL,
	Content NVARCHAR(MAX) NOT NULL,
	UpdatedDate DATETIME2 NOT NULL,
	UpdatedById BIGINT NOT NULL,
	CreatedDate DATETIME2 NOT NULL,
	CreatedById BIGINT NOT NULL,
	CategoryId INT NOT NULL,
	Viewed INT NOT NULL
)

GO
ALTER TABLE Content.Article
ADD CONSTRAINT PK_Article
PRIMARY KEY (Id);

GO
ALTER TABLE Content.Article
ADD CONSTRAINT FK_Article_Category
FOREIGN KEY (CategoryId) REFERENCES Content.Category(Id);

-- TAG --
GO
CREATE TABLE Content.Tag
(
	Id INT NOT NULL IDENTITY(1,1),
	Name NVARCHAR(50) NOT NULL,
	CreatedDate DATETIME2 NOT NULL,
	CreatedById BIGINT NOT NULL,
	UpdatedDate DATETIME2 NOT NULL,
	UpdatedById BIGINT NOT NULL
)

GO
ALTER TABLE Content.Tag
ADD CONSTRAINT PK_Tag
PRIMARY KEY (Id);

-- ARTICLE TAG --
GO
CREATE TABLE Content.ArticleTag
(
	ArticleId BIGINT NOT NULL,
	TagId INT NOT NULL
)

GO
ALTER TABLE Content.ArticleTag
ADD CONSTRAINT FK_ArticleTag_Article
FOREIGN KEY (ArticleId) REFERENCES Content.Article(Id);

GO
ALTER TABLE Content.ArticleTag
ADD CONSTRAINT FK_ArticleTag_Tag
FOREIGN KEY (TagId) REFERENCES Content.Tag(Id);

GO
ALTER TABLE Content.ArticleTag
ADD CONSTRAINT PK_ArticleTag
PRIMARY KEY (ArticleId, TagId);